#@ load("@ytt:data", "data")

#@ load("vendor/pipeline-fragments.lib.yml",
#@   "nodejs_check_code",
#@   "nodejs_audit",
#@   "build_edge_image",
#@   "release",
#@   "repo_resource",
#@   "nodejs_deps_resource",
#@   "install_yarn_deps",
#@   "deps_version_resource",
#@   "bundled_deps_resource",
#@   "version_resource",
#@   "versioned_image_resource",
#@   "charts_repo_resource",
#@   "release_task_image_config",
#@   "edge_image_resource",
#@   "public_docker_registry",
#@   "pipeline_tasks_resource",
#@   "nodejs_task_image_config",
#@   "slack_resource",
#@   "gcr_resource_type",
#@   "slack_resource_type")

groups:
- name: galoy-pay
  jobs:
    - audit
    - install-deps
    - check-code
    - build-edge-image
    - release
    - bump-image-in-chart

jobs:
- #@ install_yarn_deps()
- #@ nodejs_check_code()
- #@ nodejs_audit()
- #@ build_edge_image()
- #@ release()

- name: bump-image-in-chart
  plan:
    - in_parallel:
        - get: edge-image
          passed: [ release ]
          params: { skip_download: true }
        - get: repo
          trigger: true
          passed: [ release ]
        - get: version
          trigger: true
          passed: [ release ]
        - get: charts-repo
          params: { skip_download: true }
        - get: pipeline-tasks
    - task: bump-image-digest-in-values
      config:
        platform: linux
        image_resource: #@ nodejs_task_image_config()
        inputs:
          - name: repo
          - name: edge-image
          - name: pipeline-tasks
          - name: charts-repo
          - name: version
        outputs:
          - name: charts-repo
        params:
          BRANCH: #@ data.values.git_charts_branch
        run:
          path: pipeline-tasks/ci/tasks/bump-image-digest.sh
    - put: charts-repo-bot-branch
      params:
        repository: charts-repo
        force: true
    - task: open-charts-pr
      config:
        platform: linux
        image_resource: #@ nodejs_task_image_config()
        inputs:
          - name: pipeline-tasks
          - name: edge-image
          - name: charts-repo
        params:
          GH_TOKEN: #@ data.values.github_token
          BRANCH: #@ data.values.git_charts_branch
          BOT_BRANCH: #@ data.values.git_charts_bot_branch
        run:
          path: pipeline-tasks/ci/tasks/open-charts-pr.sh

resources:
- #@ repo_resource()
- #@ pipeline_tasks_resource()
- #@ edge_image_resource()
- #@ nodejs_deps_resource()
- #@ deps_version_resource()
- #@ bundled_deps_resource()
- #@ slack_resource()

- #@ version_resource()
- #@ charts_repo_resource()
- #@ versioned_image_resource()

- name: gh-release
  type: github-release
  source:
    owner: #@ data.values.gh_org
    repository: #@ data.values.gh_repository
    access_token: #@ data.values.github_token

- name: charts-repo-bot-branch
  type: git
  source:
    uri: #@ data.values.git_charts_uri
    branch: #@ data.values.git_charts_bot_branch
    private_key: #@ data.values.github_private_key

resource_types:
- #@ gcr_resource_type()
- #@ slack_resource_type()
