#@ load("@ytt:data", "data")

#@ load("vendor/pipeline-fragments.lib.yml",
#@   "nodejs_check_code",
#@   "nodejs_audit",
#@   "build_edge_image",
#@   "release",
#@   "repo_resource",
#@   "nodejs_deps_resource",
#@   "install_yarn_deps",
#@   "open_charts_pr",
#@   "deps_version_resource",
#@   "bundled_deps_resource",
#@   "gh_release_resource",
#@   "charts_repo_bot_branch",
#@   "version_resource",
#@   "versioned_image_resource",
#@   "charts_repo_resource",
#@   "release_task_image_config",
#@   "edge_image_resource",
#@   "public_docker_registry",
#@   "pipeline_tasks_resource",
#@   "nodejs_task_image_config",
#@   "slack_resource",
#@   "gcr_resource_type",
#@   "slack_resource_type")

groups:
- name: galoy-pay
  jobs:
    - audit
    - install-deps
    - check-code
    - build-edge-image
    - release
    - bump-image-in-chart

jobs:
- #@ install_yarn_deps()
- #@ nodejs_check_code()
- #@ nodejs_audit()
- #@ build_edge_image()
- #@ release()
- #@ open_charts_pr()

resources:
- #@ repo_resource()
- #@ pipeline_tasks_resource()
- #@ edge_image_resource()
- #@ nodejs_deps_resource()
- #@ deps_version_resource()
- #@ bundled_deps_resource()
- #@ slack_resource()

- #@ version_resource()
- #@ charts_repo_resource()
- #@ versioned_image_resource()

- #@ gh_release_resource()
- #@ charts_repo_bot_branch()

resource_types:
- #@ gcr_resource_type()
- #@ slack_resource_type()
