#@ load("@ytt:data", "data")

#@ def pipeline_image():
#@   return data.values.docker_registry + "/galoy-app-pipeline"
#@ end

#@ def release_pipeline_image():
#@   return data.values.docker_registry + "/release-pipeline"
#@ end

#@ def galoy_pay_image():
#@   return data.values.docker_registry + "/galoy-pay"
#@ end

#@ def task_image_config():
type: registry-image
source:
  username: #@ data.values.docker_registry_user
  password: #@ data.values.docker_registry_password
  repository: #@ pipeline_image()
#@ end

#@ def release_task_image_config():
type: registry-image
source:
  username: #@ data.values.docker_registry_user
  password: #@ data.values.docker_registry_password
  repository: #@ release_pipeline_image()
#@ end

groups:
  - name: galoy-pay
    jobs:
      - build-edge-image
      - release
      - bump-image-in-chart

jobs:
  - name: build-edge-image
    serial: true
    plan:
      - in_parallel:
          - { get: repo, trigger: true }
          - { get: pipeline-tasks }
      - task: prepare-docker-build
        config:
          platform: linux
          image_resource: #@ task_image_config()
          inputs:
            - name: pipeline-tasks
            - name: repo
          outputs:
            - name: repo
          run:
            path: pipeline-tasks/ci/tasks/prepare-docker-build.sh
      - task: build
        privileged: true
        config:
          platform: linux
          image_resource:
            type: registry-image
            source:
              repository: vito/oci-build-task
          inputs:
            - name: repo
          outputs:
            - name: image
          params:
            CONTEXT: repo
          run:
            path: build
      - put: edge-image
        params:
          image: image/image.tar

  - name: release
    serial: true
    plan:
    - in_parallel:
      - get: repo
        trigger: true
        passed: [ build-edge-image ]
      - get: edge-image
        passed: [ build-edge-image ]
        params:
          format: oci
      - get: pipeline-tasks
      - get: version
      - get: charts-repo
    - task: prep-release
      config:
        platform: linux
        image_resource: #@ release_task_image_config()
        inputs:
        - name: repo
        - name: pipeline-tasks
        - name: edge-image
        - name: version
        - name: charts-repo
        outputs:
        - name: version
        - name: artifacts
        run:
          path: pipeline-tasks/ci/tasks/vendor/prep-release-src.sh
    - in_parallel:
      - put: versioned-image
        params:
          image: edge-image/image.tar
          additional_tags: artifacts/gh-release-tag
      - put: gh-release
        params:
          name: artifacts/gh-release-name
          tag: artifacts/gh-release-tag
          body: artifacts/gh-release-notes.md
      - put: version
        params:
          file: version/version

  - name: bump-image-in-chart
    plan:
      - in_parallel:
          - get: edge-image
            passed: [ release ]
            params: { skip_download: true }
          - get: repo
            trigger: true
            passed: [ release ]
          - get: version
            trigger: true
            passed: [ release ]
          - get: charts-repo
            params: { skip_download: true }
          - get: pipeline-tasks
      - task: bump-image-digest-in-values
        config:
          platform: linux
          image_resource: #@ task_image_config()
          inputs:
            - name: repo
            - name: edge-image
            - name: pipeline-tasks
            - name: charts-repo
            - name: version
          outputs:
            - name: charts-repo
          params:
            BRANCH: #@ data.values.git_charts_branch
          run:
            path: pipeline-tasks/ci/tasks/bump-image-digest.sh
      - put: charts-repo-bot-branch
        params:
          repository: charts-repo
          force: true
      - task: open-charts-pr
        config:
          platform: linux
          image_resource: #@ task_image_config()
          inputs:
            - name: pipeline-tasks
            - name: edge-image
            - name: charts-repo
          params:
            GH_TOKEN: #@ data.values.github_token
            BRANCH: #@ data.values.git_charts_branch
            BOT_BRANCH: #@ data.values.git_charts_bot_branch
          run:
            path: pipeline-tasks/ci/tasks/open-charts-pr.sh

resources:
  - name: repo
    type: git
    source:
      ignore_paths: ["ci/*[^md]"]
      fetch_tags: true
      uri: #@ data.values.git_uri
      branch: #@ data.values.git_branch
      private_key: #@ data.values.github_private_key

  - name: version
    type: semver
    source:
      initial_version: 0.0.0
      driver: git
      file: version
      uri: #@ data.values.git_uri
      branch: #@ data.values.git_version_branch
      private_key: #@ data.values.github_private_key

  - name: gh-release
    type: github-release
    source:
      owner: #@ data.values.gh_org
      repository: #@ data.values.gh_repository
      access_token: #@ data.values.github_token

  - name: charts-repo-bot-branch
    type: git
    source:
      uri: #@ data.values.git_charts_uri
      branch: #@ data.values.git_charts_bot_branch
      private_key: #@ data.values.github_private_key

  - name: charts-repo
    type: git
    source:
      uri: #@ data.values.git_charts_uri
      branch: #@ data.values.git_charts_branch
      private_key: #@ data.values.github_private_key

  - name: edge-image
    type: registry-image
    source:
      tag: edge
      username: #@ data.values.docker_registry_user
      password: #@ data.values.docker_registry_password
      repository: #@ galoy_pay_image()

  - name: versioned-image
    type: registry-image
    source:
      username: #@ data.values.docker_registry_user
      password: #@ data.values.docker_registry_password
      repository: #@ galoy_pay_image()

  - name: pipeline-tasks
    type: git
    source:
      paths: [ci/tasks/*, ci/config/*, Makefile]
      uri: #@ data.values.git_uri
      branch: #@ data.values.git_branch
      private_key: #@ data.values.github_private_key
