name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        env:
          CI: false
        run: |
          echo $(ls)
          npm i
          npm run build
          rm -rf node_modules
          rm package-lock.json
          git rm -rf .
          mv build/* build/.well* .
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git pull -q
          git stash -u
          git checkout build --
          git rm -rf .
          git stash pop
          git add .
          git diff-index --quiet HEAD || git commit -m 'Build'
          git push origin build
